builds:
  - goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s
      - -w
      - -H=windowsgui
      - "-X main.version={{.Version}}"
      - "-X main.commit={{.ShortCommit}}"
      - "-X main.date={{.Date}}"
      - "-X main.branch={{.Branch}}"
    gcflags:
      - -trimpath
    hooks:
      pre:
        - go tool go-licenses save . --save_path pages/licenses/dist_licenses --force
      post:
        - go tool go-msi generate-templates --version {{.Version}} --out build-logic/ --src templates/
        - cmd /c .\scripts\post_build.bat
release:
  draft: true
  extra_files:
    - glob: dist/SabaLauncher.msi
env_files:
  github_token: .config/goreleaser/github_token
snapshot:
  version_template: "{{.Version}}+{{.Commit}}"
version: 2
